server {
    listen 443 ssl;
    server_name 146.235.233.191;

    # SSL 憑證在容器內的路徑
    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

    # 安全協定優化
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/html/html;
    index index.php index.html;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/html$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}

# 讓 HTTP 自動跳轉到 HTTPS
server {
    listen 80;
    server_name 146.235.233.191;
    return 301 https://$host$request_uri;
}
